### ISSUE TITLE
Cobertura report fails with "Duplicate key"

### ISSUE THREAD

**Issue by ggarcia24** [jenkinsci/cobertura-plugin#166]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.346.2
OS: Linux - 4.14.281-212.502.amzn2.x86_64
---
ace-editor:1.1
additional-identities-plugin:1.1
amazon-ecr:1.73.v741d474abe74
amazon-ecs:1.41
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
audit-trail:3.11
authentication-tokens:1.4
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-cloudformation:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-codebuild:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ec2:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ecr:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ecs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-elasticbeanstalk:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-iam:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-logs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-minimal:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-sns:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-sqs:1.12.246-349.v96b_b_f7eb_a_c3c
aws-java-sdk-ssm:1.12.246-349.v96b_b_f7eb_a_c3c
bitbucket-scm-trait-commit-skip:0.4.0
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-timeout:1.21
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-bitbucket-branch-source:773.v4b_9b_005b_562b_
cloudbees-folder:6.729.v2b_9d1a_74d673
cobertura:1.17
code-coverage-api:3.0.3
codebuilder-cloud:1.0.1
command-launcher:84.v4a_97f2027398
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
cucumber-reports:5.7.3
data-tables-api:1.12.1-2
display-url-api:2.3.6
docker-commons:1.19
docker-java-api:3.2.13-37.vf3411c9828b9
docker-workflow:1.29
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
favorite:2.4.1
font-awesome-api:6.1.1-1
forensics-api:1.15.1
generic-webhook-trigger:1.84
git:4.11.3
git-client:3.11.0
git-forensics:1.9.0
git-server:1.11
github:1.34.4
github-api:1.303-400.v35c2d8258028
github-branch-source:1656.v77eddb_b_e95df
google-chat-notification:1.4
google-hangouts-chat-notifier:1.0
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
jackson2-api:2.13.3-285.vc03c0256d517
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jira:3.7.1
jjwt-api:0.11.5-77.v646c772fddb_0
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
locale:180.v207501dff9b_a_
lockable-resources:2.15
mailer:414.vcc4c33714601
matrix-auth:3.1.5
matrix-project:772.v494f19991984
mina-sshd-api-common:2.8.0-21.v493b_6b_db_22c6
mina-sshd-api-core:2.8.0-21.v493b_6b_db_22c6
momentjs:1.1.1
oic-auth:1.8
okhttp-api:4.9.3-105.vb96869f8ac3a
pipeline-aws:1.43
pipeline-build-step:2.18
pipeline-config-history:1.6
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:593.va_a_fc25d520e9
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2097.v33db_b_de764b_e
pipeline-model-definition:2.2097.v33db_b_de764b_e
pipeline-model-extensions:2.2097.v33db_b_de764b_e
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2097.v33db_b_de764b_e
pipeline-stage-view:2.24
plain-credentials:1.8
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
prism-api:1.28.0-2
pubsub-light:1.16
resource-disposer:0.19
role-strategy:530.ved5445d4875a_
saml:2.298.vc7a_2b_3958628
scm-api:608.vfa_f971c5a_a_e9
script-security:1175.v4b_d517d6db_f0
simple-theme-plugin:103.va_161d09c38c7
snakeyaml-api:1.30.2-76.vc104f7ce9870
sse-gateway:1.25
ssh-credentials:291.v8211e4f8efb_c
ssh-slaves:1.821.vd834f8a_c390e
sshd:3.242.va_db_9da_b_26a_c3
structs:318.va_f3ccb_729b_71
timestamper:1.18
token-macro:293.v283932a_0a_b_49
trilead-api:1.66.v49c6758b_b_360
variant:1.4
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:969.vc4ec3e4854b_f
workflow-cps:2746.v0da_83a_332669
workflow-durable-task-step:1174.v73a_9a_17edce0
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:833.va_1c71061486b_
ws-cleanup:0.42
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins master: Docker Image jenkins/jenkins:lts
Jenkins slaves: Docker Image jenkins/inbound-agent:4.11-1-jdk11

### Reproduction steps

Hello!

I've reported an issue in the [Jenkins Jira instance](https://issues.jenkins.io/browse/JENKINS-69046), but I'm not sure if that's being reviewed by someone or not, so I'm also adding my report here, I'm really sorry if that causes any inconveniences and please close the one that's in the right place.

---

After updating the my jenkins instance plugins (cobertura was updated to version 1.17) I started getting error when publishing coverage and when trying to open the reports.

My Jenkinsfile has the following post stage action:

```text
            post {
                always {
                    junit '**/output/reports/**/*.xml'
                    cobertura coberturaReportFile: 'components/**/coverage/cobertura-coverage.xml',
                        enableNewApi: true,
                        autoUpdateHealth: false,
                        autoUpdateStability: false,
                        failUnhealthy: false,
                        failUnstable: false,
                        conditionalCoverageTargets: '70, 0, 0',
                        lineCoverageTargets: '80, 0, 0',
                        methodCoverageTargets: '80, 0, 0',
                        maxNumberOfBuilds: 1
                }
            } 
```

Our company code convention follows the following schema:

```text
components
|- <COMPONENT_NAME>
    |- src
        |- handlers.ts
        |- package.json
```

Which means that it's normal for us to have multiple files named `handlers.ts` in the same project (but part of a different "package"):

```text
- components
|- api/src/handlers.ts
|- messaging/src/handlers.ts
|- triggers/src/handlers.ts
```

The code inside handler is not that important as it's usually related to dependency injection, I do not remember the behavior before the update (I think they were all merged in the "main/src/handler.ts", hence not being correct, but it wasn't the point as it's not of interest for us, what I do remember was that the plugin was not causing any build problems like now)

### Expected Results

Pipeline runs successfully

### Actual Results

When the pipeline runs I'm getting this:

```text
[Pipeline] junit
12:41:03  Recording test results
12:41:04  [Checks API] No suitable checks publisher found.
[Pipeline] cobertura
12:41:04  [Cobertura] Publishing Cobertura coverage report...
12:41:04  
12:41:04  [Cobertura] Publishing Cobertura coverage results...
12:41:04  
12:41:04  [Cobertura] Cobertura coverage report found.
12:41:04  
12:41:04  Publishing Coverage report....
12:41:05  A total of 4 reports were found
12:41:05  Report coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Group coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Package coverage diff: 0.0%. Add to CoverageResult.
12:41:05  File coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Class coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Method coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Line coverage diff: 0.0%. Add to CoverageResult.
12:41:05  Conditional coverage diff: 0.0%. Add to CoverageResult.
12:41:05  [Coverage] Computing coverage delta report
12:41:05  [Coverage] Reference build recorder is not configured
12:41:05  [Coverage] -> No reference build defined, falling back to previous build
12:41:05  [Coverage] -> Found reference result 'io.jenkins.plugins.coverage.CoverageAction@1cfc78a0'
12:41:05  [Coverage] Obtaining action of reference build
12:41:05  [Coverage] Reference build recorder is not configured
12:41:05  [Coverage] -> No reference build defined, falling back to previous build: '#2'
12:41:05  [Coverage] -> Found reference result in build '#2'
12:41:05  The recommended git tool is: NONE
12:41:05  using credential **redacted**
12:41:05  The recommended git tool is: NONE
12:41:05  using credential **redacted**  
Error when executing always post condition:
java.lang.IllegalStateException: Duplicate key main/src/handlers.ts (attempted merging values [File] src/handlers.ts and [File] src/handlers.ts)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.jenkins.plugins.coverage.model.FileChangesProcessor.attachChangedCodeLines(FileChangesProcessor.java:41)
	at io.jenkins.plugins.coverage.model.CoverageReporter.run(CoverageReporter.java:101)
	at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:133)
	at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:114)
	at io.jenkins.plugins.coverage.adapter.CoverageReportAdapter.performCoveragePlugin(CoverageReportAdapter.java:140)
	at io.jenkins.plugins.coverage.adapter.CoverageReportAdapter.performCoveragePlugin(CoverageReportAdapter.java:121)
	at hudson.plugins.cobertura.CoberturaPublisher.perform(CoberturaPublisher.java:628)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[Pipeline] } 
```

### Anything else?

An extra weird thing is that sometimes I can open the coverage report and sometimes I get this NPE in the Jenkins logs (unsure if it's related or if it's a different issue)

```text
 Caught exception evaluating: from.lastResult.result in /job/**redacted**/job/develop/. Reason: java.lang.reflect.InvocationTargetException java.lang.NullPointerException Caused: java.lang.reflect.InvocationTargetException at jdk.internal.reflect.GeneratedMethodAccessor988.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125) at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314) at org.apache.commons.jexl.parser.ASTArrayAccess.evaluateExpr(ASTArrayAccess.java:185) at org.apache.commons.jexl.parser.ASTIdentifier.execute(ASTIdentifier.java:75) at org.apache.commons.jexl.parser.ASTReference.execute(ASTReference.java:83) at org.apache.commons.jexl.parser.ASTReference.value(ASTReference.java:57) at org.apache.commons.jexl.parser.ASTReferenceExpression.value(ASTReferenceExpression.java:51) at org.apache.commons.jexl.ExpressionImpl.evaluate(ExpressionImpl.java:80) at hudson.ExpressionFactory2$JexlExpression.evaluate(ExpressionFactory2.java:76) at org.apache.commons.jelly.tags.core.CoreTagLibrary$3.run(CoreTagLibrary.java:134) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:99) at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:172) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161) at org.apache.commons.jelly.tags.core.ForEachTag.doTag(ForEachTag.java:150) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:99) at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:172) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101) at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101) at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101) at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91) at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:265) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122) at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122) at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105) at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:99) at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:66) at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:55) at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:56) at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:43) at org.kohsuke.stapler.Facet.handleIndexRequest(Facet.java:284) at org.kohsuke.stapler.jelly.JellyFacet.handleIndexRequest(JellyFacet.java:105) at org.kohsuke.stapler.IndexViewDispatcher.dispatch(IndexViewDispatcher.java:32) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898) at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289) at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898) at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289) at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898) at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289) at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694) at org.kohsuke.stapler.Stapler.service(Stapler.java:240) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157) at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:42) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:112) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:60) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154) at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94) at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:102) at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:93) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111) at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:516) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) at java.base/java.lang.Thread.run(Thread.java:829)
Jul 18, 2022 11:25:06 AM WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException
Caught unhandled exception with ID be316bf5-0a54-45a6-b931-9b4eb45d8479 java.lang.NullPointerException
```

I attempted to revert to the previous version reported by Jenkins (1.16) but it doesn't seem to solve the issue, I'm guessing that something has changed in another dependency and it's causing the issue, but I'm lost on where to start troubleshooting the issue.

Does anybody has a suggestion on where to start? (i.e revert to version XXX, change pipeline definition, ...)

Best regards
Gonzalo G

**Comment by ggarcia24** [comment]
I think this is issue is related to this other one: https://github.com/jenkinsci/code-coverage-api-plugin/issues/433

According to what I can understand from that issue downgrading `code-coverage-api-plugin` to 2.0.4 should resolve the issue

**Comment by uhafner** [comment]
Interesting. Seems that the cobertura plug-in calls code of the code coverage plug-in. Actually these plugins should work independently. This problem indeed has the same root cause.

Can you elaborate why you are using the cobertura plug-in and not the code coverage plug-in? Maybe we can improve the code coverage plug-in so that it is not required to use the cobertura plug-in anymore. 

Can we use your cobertura xml files in the test cases of the code coverage plug-in. I think we still have not enough examples for cobertura reports in the moment.

**Comment by ggarcia24** [comment]
I can confirm that updating to `code-coverage-api-plugin@v3.0.5` solved this issue! 🥳 
 
To be honest I just recently learned about the existence of the `code-coverage-api-plugin` because of this issue, I really like the way the it displays the values, also it seems to calculate the coverage a little bit more accurately

But the cobertura plugin displays a "drill down" of the source code (Package -> File -> Code), which is very helpful when we want to analyze coverage:

Package:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/452494/184450756-568dfab1-95e8-4338-8a32-bf6891634211.png">

Files:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/452494/184450939-4f3b9bfd-9df2-4ad8-9858-f99fd5765064.png">

Code:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/452494/184448548-7c96c726-cf8f-4da0-8be4-db03facaefdb.png">

**Comment by uhafner** [comment]
Thanks for the feedback! A drill down to the source code is available as well. I just removed the drill downs from module to package to file as I do  not see a big help for my projects. Maybe I should restore those views in additional tabs. Please note that the code coverage API has the unique feature of showing delta reports (of pull requests). 

Is there a chance that you can send us an (anonymized) versions of your Cobertura reports? We are currently improving the Cobertura and JaCoCo parsers and it seems that we cannot find enough Cobertura examples (Cobertura seems to be dead and does not support new Java versions anymore).

**Comment by ggarcia24** [comment]
Sorry for the delay, yes! I can send you the report files, a small notice though, I'm currently using cobertura mainly because it's was the only way I knew to put Jest coverage reports in Jenkins, but I see that your plugin supports Istanbul; I'll have to look how to configure things, but it's very likely that I switch to your plugin

Small usability question: How do I get from here to the see the code (last picture in my example): 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/452494/187841769-63565899-89c5-4236-8a5b-5051614bee0c.png">
