### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space or how to reducing memory usage by plugin?

### ISSUE THREAD

**Issue by f33r0** [jenkinsci/cobertura-plugin#220]
### Jenkins and plugins versions report

```
 [Cobertura] Publishing Cobertura coverage report...
 [Cobertura] Publishing Cobertura coverage results...
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at hudson.plugins.cobertura.CoberturaXmlHandler.characters(CoberturaCoverageParser.java:330)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.characters(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.characters(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.SAXParser.parse(Unknown Source)
	at hudson.plugins.cobertura.CoberturaCoverageParser.parse(CoberturaCoverageParser.java:78)
	at hudson.plugins.cobertura.CoberturaCoverageParser.parse(CoberturaCoverageParser.java:52)
	at hudson.plugins.cobertura.CoberturaPublisher.perform(CoberturaPublisher.java:596)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$872/0x00000001012dbd00.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

docker linux

### Reproduction steps

1. run coverage test
2. error

### Expected Results

Publishing coverage report

### Actual Results

java.lang.OutOfMemoryError: Java heap space

**Comment by jeffpearce** [comment]
Do you by chance have the coverage file from the job? It would make it easier to debug
